### ISSUE TITLE
[NBug] 'C:\Users\mbarry\AppData\Local\Programs\Git\bin\git.exe config --includes --get user.name' returned non-zero exit code.

### ISSUE THREAD

**Issue by mamadou64** [gitextensions/gitextensions#11366]
### Environment

- Git Extensions 4.2.0.17591
- Build bf814d4f1c6f178eacef38d592b700f9f2519dcb
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.24
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

Exit code: 1
Command: C:\Users\mbarry\AppData\Local\Programs\Git\bin\git.exe
Arguments: config --includes --get user.name
Working directory: C:\Git\DevApps\

```
GitExtUtils.ExternalOperationException: External program returned non-zero exit code.
 ---> System.Exception: External program returned non-zero exit code.
   --- End of inner exception stack trace ---
   at async Task<string> GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, byte[] input, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes) in C:/projects/gitextensions/GitCommands/Git/ExecutableExtensions.cs:line 129
   at void Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTask<T>.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run<T>(Func<Task<T>> asyncMethod, JoinableTaskCreationOptions creationOptions) x 2
   at string GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, byte[] input, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes) in C:/projects/gitextensions/GitCommands/Git/ExecutableExtensions.cs:line 43
   at string GitCommands.GitModule.GetEffectiveGitSetting(string setting, bool cache) in C:/projects/gitextensions/GitCommands/Git/GitModule.cs:line 2421
   at async void GitUI.CommandsDialogs.FormCommit.UpdateAuthorInfo()+(?) => { } in C:/projects/gitextensions/GitUI/CommandsDialogs/FormCommit.cs:line 2726
   at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 38
```

update

### Steps to reproduce

bug after update

**Comment by mamadou64** [comment]
error on application after update

**Comment by gerhardol** [comment]
You have not set the Git user name and maybe not the email, so you cannot commit.

This popup is for the lower left indication.
Maybe ignore the issue here and show the Git error only when pressing commit?

**Comment by mamadou64** [comment]
yes when pressing commit ?


*Mamadou BARRY*


Le sam. 18 nov. 2023 à 13:54, Gerhard Olsson ***@***.***> a
écrit :

**Comment by mstv** [comment]
Wasn't there something red?

![image](https://github.com/gitextensions/gitextensions/assets/36601201/755ecb24-32b7-46e7-801a-3f3ff4e10e6a)

**Comment by mamadou64** [comment]
I entered my username and email and that solved my problem.

thanks you

*Mamadou BARRY*


Le sam. 18 nov. 2023 à 15:47, Michael Seibt ***@***.***> a
écrit :

**Comment by mstv** [comment]
The issue is that the exception cannot easily be ignored. The command is repeated right afterwards because of

```
        protected override void OnActivated(EventArgs e)
        {
            if (!_bypassActivatedEventHandler)
            {
                UpdateAuthorInfo();
            }

            base.OnActivated(e);
        }
```

**Comment by ChaerilM** [comment]
i use my git inside wsl2, the gitextension work until yesterday, i think after i added systemctl to wsl2 via some hacky way. then realized i could just add it via wsl.conf

**Comment by mamadou64** [comment]
Hello,

GitExtension: when I click on commit the gitExtention application crashes?
Could you help me ?
*Mamadou BARRY*

**Comment by mstv** [comment]
> Hello, GitExtension: when I click on commit the gitExtention application crashes? Could you help me ? *Mamadou BARRY*

What is different from your https://github.com/gitextensions/gitextensions/issues/11366#issuecomment-1817529221?

**Comment by mstv** [comment]
Fixed in v4.2.1

**Comment by mamadou64** [comment]
So I just need to update the version?


Le mer. 20 déc. 2023 à 17:54, Michael Seibt ***@***.***> a
écrit :

**Comment by sharwell** [comment]
Duplicate of #11364

**Comment by mamadou64** [comment]
I defined my username and email but that doesn't solve the problem of
crashing when I click on commit.
For version 4.2.1 how I can update.
I tried to install the new one on the old one but it works.



Le mer. 20 déc. 2023 à 19:00, Gerhard Olsson ***@***.***> a
écrit :
