### ISSUE TITLE
Diff and commit view - cp1251 encoding cannot be selected and used correctly

### ISSUE THREAD

**Issue by zlolik** [gitextensions/gitextensions#12112]
### Environment

- Git Extensions 5.1.1.17970
- Build 939c0edba68f0c15b8e5180ca06a92c5ce534501
- Git 2.47.0.windows.2
- Microsoft Windows NT 10.0.22621.0
- .NET 8.0.11
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Sometimes codepage cp1251 file looks incorrectly.

1. Add new file - encoding can't be selected, view is broken and different when staged:
![Image](https://github.com/user-attachments/assets/911f657d-c323-4201-8179-fadf366eb484)

2. Update this file - encoding can be selected, but only for new lines:
![Image](https://github.com/user-attachments/assets/ca2087f2-8c21-43c9-9656-89d201f88396)

3. Diff view of this file - encoding can be selected only when file changed, but only for new lines:
![Image](https://github.com/user-attachments/assets/753344de-da0a-4c5f-8dc2-0b65991f2587)

### Steps to reproduce

See description, example repo is https://github.com/zlolik/cp1251

**Comment by pmiossec** [comment]
Could you test the last dev portable version to see if it is a duplicate of #12066 and fixed by #12091 ?

You could get here: https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts

**Comment by zlolik** [comment]
Issue desciption has been updated. 2 and 3 - are duplicated. But adding new file is still without codepage selector.

**Comment by mstv** [comment]
You could try the global encoding settings. A restart of GE is required.

![Image](https://github.com/user-attachments/assets/e3cb6112-87bc-4ec1-b722-1f67a4f475fb)

**Comment by zlolik** [comment]
Global encoding setting is not an option - we have files with both encoding utf8 and cp1251.

**Comment by alex-mamutov** [comment]
Hello! I confirm the problem: it is present in the latest release (6.0.5.18375). The diff window and file content in File Tree both misinterpret cp1251 as UTF-8. The diff window does show a toolbar where I can set the encoding manually but only if the change is a content change. No toolbar if the file is just added (and no way to adjust the encoding). The file content part of the "File Tree" tab never has any toolbar, hence there is no way to set the encoding.

Regarding the advice from @mstv ("global encoding settings"). It didn't work. I changed it, did restart - it had no effect on GE.

**Comment by mstv** [comment]
> Issue desciption has been updated. 2 and 3 - are duplicated. But adding new file is still without codepage selector.

Yes, this is a known limitation. (git-grep is affected, too.)

> Global encoding setting is not an option - we have files with both encoding utf8 and cp1251.

If you use UTF8 without BOM, you have no chance because cp1251 cannot be distinguished from other code pages.
UTF8 with BOM should automatically be detected - at least for diffs at the moment. Then setting cp1251 as default should solve the issue - for diffs. This can be set per repo.
Different code pages in one repo cannot be handled. It would require a setting per file type or whatever.
Edit: Using the codepage selector might be an option.

**Comment by alex-mamutov** [comment]
> Using the codepage selector might be an option.

Unfortunately, it doesn't solve the general problem. It only works for diff window and only if there is a local diff change, like some lines are changed, and others are not. If the diff is the entire file, when the file is just added, then the setting is not working and the toolbar with the encoding is not shown AND the file is always shown in utf-8. Same is for the File Tree viewer. Since it doesn't show any changes, just the whole file content, there is no toolbar AND it is always in utf-8 regardless of the encoding setting.

I understand that ASCII based encodings are indistinguishable from each other. That's ok as long as there is a way to set the setting manually.

**Comment by mstv** [comment]
Yes, with "Using the codepage selector might be an option.", I mean(t) "showing (and applying) this selector also when showing plain files", i.e. not only for diff/patch.
"applying" will need _some_ work to be done I guess.
