### ISSUE TITLE
Method not found error after upgrade to 6.0.2 from 5.x

### ISSUE THREAD

**Issue by vtintillier** [gitextensions/gitextensions#12637]
### Environment

- Git Extensions 6.0.2.18262
- Build f02a06bf5366bcee241c3273951de3a132020b48
- Git 2.51.2.windows.1
- Microsoft Windows NT 10.0.26200.0
- .NET 9.0.10
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 9.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

After upgrading to 6.0.2 (from a very recent 5.x version, I update quite often), I get this error when opening a repository, or after any action that triggers commits tree refresh:

<img width="410" height="171" alt="Image" src="https://github.com/user-attachments/assets/aba70142-e0b5-4d48-a8f4-5a4e551e9a4b" />

```
Method not found: '!!0 GitUI.ControlUtil.FindDescendantOfType(System.Windows.Forms.Control, System.Func`2<!!0,Boolean>, System.Func`2<System.Windows.Forms.Control,Boolean>)'.
```

### Steps to reproduce

Just upgraded the package via `winget`.

### Did this work in previous version of GitExtensions?

Yes, in one of the last, or last, 5.x version.

**Comment by pmiossec** [comment]
Have you got external plugins ? Could you try to update them?

**Comment by vtintillier** [comment]
I had already checked for updates, and found nothing:

<img width="771" height="588" alt="Image" src="https://github.com/user-attachments/assets/7911c257-ed75-4d17-80d9-bd627b3fbee4" />

But looking in the _Installed_ tab, I see Gerrit plugin is marked as _Not compatible_, and indeed in a repository using Gerrit, the icons in toolbar are not there anymore.

<img width="776" height="585" alt="Image" src="https://github.com/user-attachments/assets/dc8b20b6-7640-4dc1-95fe-83872284f0fd" />

Apparently this is issue is fixed already by https://github.com/gitextensions/GitExtensions.GerritPlugin/pull/89, just not update shows in Plugin Manager.

Should I just remove the plugin and install the last version manually, or is it interesting to understand why the new version does not show up in _Updates_ tab?

**Comment by pmiossec** [comment]
I think it is the Gerrit plugin the problem but the package ( 
https://github.com/gitextensions/GitExtensions.GerritPlugin/releases/tag/v3.1.1 ) has still not be published due to a problem of token to upload it 🫤

Maybe  download and install it manually.

**Comment by vtintillier** [comment]
How can we install it manually? What should I download?

I also created https://github.com/gitextensions/GitExtensions.GerritPlugin/issues/91 as not only 3.1.1 is missing.

**Comment by gerhardol** [comment]
> How can we install it manually? What should I download?
> 
> I also created [gitextensions/GitExtensions.GerritPlugin#91](https://github.com/gitextensions/GitExtensions.GerritPlugin/issues/91) as not only 3.1.1 is missing.

follow the link for a pr with builds, go to history and check the lastest master builds, look for the artifact
