### ISSUE TITLE
Allow multiple branches for advanced branch filter

### ISSUE THREAD

**Issue by berniegp** [gitextensions/gitextensions#3546]
#1285 introduced a very useful feature to use the contents of the taskbar filter to build a `--branches=[FILTER]` parameter for `git log`.

I would like to use the filter taskbar to display multiple branches such as:
 - `users/berniegp/*`
 - `master`

However, since all the text of the taskbar filter is sent to a single `--branches` parameter, this is not possible. A possible solution would be to split the contents of the filter on whitespace to build multiple `--branches` parameters.

Also see this [stackoverflow question](http://stackoverflow.com/questions/42375821/git-log-branches-with-multiple-branches-using-glob-patterns)

**Comment by azarkevich** [comment]
Actually text from branch filter inserted into git command line as-is (or prefixed by `--branches=`) without escaping or somethig similar. Which means that you can add arbitrary git options.

So your case can be solved with GitExt 2.49, though it is cumbersome...

Here is next tricks:
1. if branch filter contains globing symbols, then GitExt prefixed it with `--branches=`
2. git does not accept more than one branch for log, so you should use `--branches` for every branch
3. for remote branches should be used `--remotes`
4. if used branch without globing, then git automatically add `/*` to end of branch, so you can't use `--branches=master`, instead you should use `--branches=maste[r]` with fake globing

Some examples:

1. `users/berniegp/* --branches=maste[r]`

Should do what you asking for. It will be converted by GitExt to `--branches=users/berniegp/* --branches=maste[r]`

2. `users/berniegp/* --branches=maste[r] --remotes=origin/users/berniegp/*`

Also show remote tracking branches (origin/users/berniegp/*)

3. `--reflog`

Show also commits which references from reflog. May be useful for find 'lost' commits?

4. `--bisect`

Should (I don't try it actually) show range of commits where problem was introduced (between good and bad)

5. `--reverse`

Show commits in reverse order.

And other options of `git log` (https://git-scm.com/docs/git-log)

**Comment by Dimitri0xff** [comment]
I also need this feature, my use case is that I have multiple remotes and I would like to filter the branches to view only one of the remotes at once.

**Comment by RussKie** [comment]
You can hide/show remotes via the Remote form

![image](https://user-images.githubusercontent.com/4403806/37593593-9a118a52-2bc6-11e8-8f07-8003bfe89880.png)

**Comment by Dimitri0xff** [comment]
Thank you that works. I had an older version so had no chance to find it.

Only problem is when I activate the remote again, I also must do a fetch to see it. I don't see why a refresh is not enough to see its branches again.

**Comment by RussKie** [comment]
i couldn't get git to recognise the enabled remote. ideas and suggestions
are welcome

**Comment by qwertie** [comment]
This isn't working for me in Git Extensions 3.1.0.5877. In fact, when I write any branch name with a glob in it to the "Branches:" textbox, one of two things happens, seemingly at random: 

1. the history list is blank.
2. the history list shows all commits on all branches.

**Comment by hieuxlu** [comment]
> But this is no longer happening.

@qwertie Probably got fixed in #7204. Now in master build, there's should be a <No result found> item instead of an empty list.

As per tiny comments below accepted answer of https://stackoverflow.com/questions/5316802/does-git-log-branches-work, git log support below syntax
`git log branch1 branch2`
I think that would be better than patterns if we want to filter multiple branches by exact name. I'll probably use this for #6180 , another feature request related to filtering multiple branches (on the GUI)

**Comment by pmiossec** [comment]
>Probably got fixed in #7204. Now in master build, there's should be a item instead of an empty list.

To clarify, the placeholder item (see #7271) is here to fix the exception but don't change the behavior and don't prevent the user the pass arguments to the `git log` command run.

**Comment by Boddlnagg** [comment]
I used the trick from https://github.com/gitextensions/gitextensions/issues/3546#issuecomment-284317068 to setup this advanced filter: `--branches=* --remotes=[o]rigin/master`
The intention was that I would see all local branches as well as the `origin/master` remote branch.
In version 3.5 this does not work anymore: I still see `origin/master`, by I don't see my local branches any more, not even the one I have currently checked out.

**Comment by szabi** [comment]
> to setup this advanced filter: `--branches=* --remotes=[o]rigin/master`

Per the trick comment you should enter **only** `* --remotes=[o]rigin/master` into the text box. The first `--branches=` is added automatically in the background (if the funnel dropdown is set to "local", which is the default if you did not change it).

Then it works for me on 3.5.0.11713

**Comment by Boddlnagg** [comment]
> Per the trick comment you should enter only `* --remotes=[o]rigin/master` into the text box.

Thanks, this works for me, too! Apparently I had misunderstood the original comment, and my version including `--branches=` used to work before 3.5 as well.

**Comment by h0lg** [comment]
How about selecting branches from the left branch tree panel?
https://github.com/gitextensions/gitextensions/issues/3114#issuecomment-503377888
https://github.com/gitextensions/gitextensions/discussions/9495#discussioncomment-1606019
https://github.com/gitextensions/gitextensions/issues/3114#issuecomment-503317476

**Comment by RussKie** [comment]
Copying the comment from https://github.com/gitextensions/gitextensions/issues/3165#issuecomment-964041910

> It is possible today to only show selected branches. Perhaps it is not as obvious or as fluent as it could have been, but it is relatively straight forward - use the Advanced filter.
> 
> Here's a screenshot from the dev build (in v3.x it is not as refined) - I'm filtering only to three branches: "msi", "test" and "fix_nre": ![image](https://user-images.githubusercontent.com/4403806/140912144-c8c20eb2-a3e7-4c3b-8222-2802ade48110.png) It is worth noting that the dev version has a bug where the toolbar branch filter combo isn't updated with the filter, but it would have the same filter value as well.

The toolbar combo has to be scrapped and reimplemented using a [`ToolStripControlHost` control](https://docs.microsoft.com/dotnet/api/system.windows.forms.toolstripcontrolhost) to be something similar to the Excel's data filter:
![image](https://user-images.githubusercontent.com/4403806/140914482-6c7a3a45-1c6b-4860-ab02-78821cf2b507.png)


> How about selecting branches from the left branch tree panel?

This may be useful. In fact it is partially working - i.e. it is possible to filter to a specific branch:
![image](https://user-images.githubusercontent.com/4403806/140913950-25eef3b2-6cee-4eff-a63a-b76f7d17c40e.png)

It would be useful to extend it to something like _add to the current filter_ (if a filter is set).

**Comment by h0lg** [comment]
@RussKie Thanks for the heads up. The advanced filter is something that I have up until now only stumbled upon accidentally when I wanted to find something in the diff view or file explorer and had the revision grid focused instead. I don't even know how to open it from the UI and have found it too hard to understand to actually try and use it.

Also, I the branch filter in there I consider even less useful than the one in the toolbar because it doesn't auto-complete existing branch names. Especially with longer branch names than in your example that would be important if you require me to type them in.

The fact that the branch tree is already working to filter for a single branch was why I suggested to use it as a starting point for operations on multiple branches, like filter the revision grid by them. It already has a search, contains all branches and wouldn't require typing. Seems like a natural fit to me.

**Comment by RussKie** [comment]
Yes, the advanced filter can be further improved in many ways... E.g.,
replacing the textbox with the branch selector control (that is used in
FormBranchDelete) is probably won't be too difficult...

This is a community project, and we accept PRs 😉

**Comment by crossan007** [comment]
It's worth noting that the proposed "cumbersome" solution here also facilitates _excluding branches matching a pattern_

I've been trying to do this for a while when I stumbled on this thread.  My use case is as follows:

I have many (~50) branches which have a prefix of `client/*`  which I'd like to exclude from my view at development time (while still including all, or select, other branches).  

Git log supports this behavior naively: https://git-scm.com/docs/git-log

```List commits that are reachable by following the parent links from the given commit(s), but exclude commits that are reachable from the one(s) given with a ^ in front of them. The output is given in reverse chronological order by default.```

However when I tried to use multiple filter strings (expecting them to behave as individual `--branches` parameters) (e.g. `^client/* feature/*`) in Git Extensions, I was shown zero branches, instead of the ones I expected.

*THE KEY HERE* is to include the `--branches` string in the filter text box; like this: `^client/* --branches=feature/*`.  This filter text correctly shows me all `feature/*` branches, while excluding `client/*` branches.

**Comment by h0lg** [comment]
@crossan007 I'm working on https://github.com/gitextensions/gitextensions/pull/9723 which will allow you to construct a positive list of branches to filter for from the left hand branch panel. Since that panel already groups branches into folders by common prefixes such as `client/`, it will allow you to (de-)select all branches in such a folder using a single `Ctrl` click. So I hope it will meet your specific requirement even though it doesn't aim for the full flexibility of the functionality you describe.
