### ISSUE TITLE
Webroot and zonealarm

### ISSUE THREAD

**Issue by john1726** [gitextensions/gitextensions#3724]
When I download your zip file or clone it, and scan it on virus total, I get 2 hits so I can't install Git Extensions at work.  Do you have any suggestions?  TIA.

[https://ibb.co/eoHmkv](https://ibb.co/eoHmkv)

**UPDATE:**

Also, if I try to download and use your MSI I get a detection from Trend Micro:

[https://ibb.co/iKfQTF](https://ibb.co/iKfQTF)

The weirdest thing is that when I scan the MSI in chrome there are not detections but when I scan it with IE there is 1 detection.

**Comment by jbialobr** [comment]
Where did you download that files from? I got 0 / 55 while scanning the original file I released.

**Comment by jbialobr** [comment]
Sorry, I scanned a wrong file - generated 2 days later. The original file is the same as we can download from github and sourceforge.

**Comment by jbialobr** [comment]
When zipped the TranslationApp.exe gets one hit:
`TrendMicro-HouseCall	Suspici.692BA229	20170525`
But once scanned unziped it gets zero hits. I think those hits are false positives.

**Comment by john1726** [comment]
What do you mean scanning it unzipped it gets zero hits?  I tried extracting the MSI file and then scanning the GitExtensions.zip and I still get a detection.  How do you know it is the TranslationApp.exe that it getting the hit?  Did you scan each file individually?

Can I install this Git Extensions without the TranslationApp.exe?

**Comment by jbialobr** [comment]
I did a scan for https://github.com/gitextensions/gitextensions/releases/download/v2.49.03/GitExtensions-2.49.03-Mono.zip. It gave one hit. Then with bisecting I found that the the only file causing problems is the TranslationApp.exe. I scanned it unzipped and it did not give any hits. Then I zipped only this single file and got a hit for that zip. This proves that the service is not reliable.
