### ISSUE TITLE
System.NullReferenceException when trying to push

### ISSUE THREAD

**Issue by AliMirlou** [gitextensions/gitextensions#3862]
Happens when trying to push, no matter how (Choosing push from Commands or toolbar, using push hotkey (ctrl+up), "Commit and Push" in commit window). Giving me "System.NullReferenceException: Object reference not set to an instance of an object." on "Void UpdateRemoteBranchDropDown() @ GitUI.CommandsDialogs.FormPush" by opening a crash report window.

The problem started after installing GitExtensions 2.50.01 (Git 2.10.0, Windows 10 version 1703 build 15063.483).
Redownloaded and reinstalled but no luck.

There are many graphical bugs too, some related to being incompatible with 4k resolution, which i don't know if i have to open issues for them or not.

**Comment by RussKie** [comment]
Please raise all issues you have. If we don't know them - we can't fix them.

**Comment by Alimirlou** [comment]
@RussKie They're hard to explain but i will definitely. But for now, this bug has higher priority for me. Any ideas?

**Comment by RussKie** [comment]
As an immediate work around - please try installing 2.49.x version and see if it works for you.

**Comment by RussKie** [comment]
Can you successfully perform other operations - e.g. pull, fetch, checkout?
Can you please provide more info on your issue? E.g. the full stack trace, any screenshots.

**Comment by Alimirlou** [comment]
@RussKie previous versions work well. And as far as i tested, Yes, other operations work and the problem seems to be only related to push dialog window. Here's a screenshot but i'm not sure if it helps:
![1](https://user-images.githubusercontent.com/19661419/28369194-23fa6304-6cac-11e7-8a1c-2172bdf771a6.png)
I'm not really familiar with the debugging tools to provide you with more info, is there a document for it?

**Comment by vbjay** [comment]
The details under the exception tab would be more helpful.

**Comment by Alimirlou** [comment]
@vbjay Unfortunately, this is where one of the graphical bugs are:
![1](https://user-images.githubusercontent.com/19661419/28385675-3acf1e94-6cde-11e7-899d-0f7c4229dea5.png)

**Comment by vbjay** [comment]
Lol. Nice.

**Comment by EbenZhang** [comment]
do you have at least one remote? just fixed a NPE in this function few days ago.

**Comment by Alimirlou** [comment]
@EbenZhang Yes, I have remotes. When will this fix be added to the builds?

**Comment by dogancelik** [comment]
Same problem, happened when I init'ed a new fresh repo, staged and commited files, click Push button then NPE error. Version: 2.50.01

**Comment by vbjay** [comment]
Upgrade git.

**Comment by RussKie** [comment]
@dogancelik have you set at least one remote before pushing?
it is unclear from your description whether you have done or missed this step.

**Comment by dogancelik** [comment]
I was in a hurry so I didn't explain it well.
This error occurs in **2.50.00** and **2.50.01**:

### Before 2.50
1. I open an empty folder with `GitExtensions browse folder-path`
2. I click "Initialize repository"
3. I stage a single text file and commit with "Initial"
4. I click "Push", dialog opens

![24903](https://user-images.githubusercontent.com/486818/28600915-d2564434-71bd-11e7-8533-b459ee4673b2.png)

### After 2.50
1. I open an empty folder with `GitExtensions browse folder-path`
2. I click "Initialize repository"
3. I stage a single text file and commit with "Initial"
4. I click "Push", **exception error**

![25001](https://user-images.githubusercontent.com/486818/28600916-d25b07bc-71bd-11e7-994c-b18c17a78586.png)

You don't even need Step 3.
In **2.49.03**, it works whether you commit a file or not.
The error occurs because there is no remote.
I didn't find the need to explain the issue as issue author already explained it.

**Comment by RussKie** [comment]
Awesome, thanks for the explanation and screenshots.
I'll try to replicate this

**Comment by RussKie** [comment]
This issue was fixed by @EbenZhang in 11d2763b9bf1babdc237bb56fdd23a82b6b0c00b
However it is yet to be published

**Comment by maxim-grinchenko** [comment]
I have the same problem... http://take.ms/yq7Eg

**Comment by vbjay** [comment]
@maxima  Read Russkie's comment.

**Comment by RussKie** [comment]
I'm closing this. 
Please re-open if the issue re-occurs in 2.50.02 (once it is released)

**Comment by Crowley2012** [comment]
I cloned the current branch and the issue is still there for me.

**Comment by RussKie** [comment]
the current 2.50 branch or the master?

I just tried it built from both the master and origin/release/2.50 branches and observed no issues
![image](https://user-images.githubusercontent.com/4403806/29445589-03e11f40-842b-11e7-823d-ad3729a063bd.png)

**Comment by Crowley2012** [comment]
The master branch, the push menu opens but when I actually try to push to a remote server it crashes.

**Comment by nforss** [comment]
I'm running into a similar problem, too. It was proceeded by Git Extensions becoming completely unresponsive, and the only way I could get it shut down was a reboot. Task manager -> End task or even command line (as admin) taskkill /F didn't do a thing.

After the reboot I get NullReferences whenever I try to pull from or push to origin. Below is the resulting error message. I can get the pull and push to go through by manually inputing my username and password, but the problem persists between pushes and pulls.

```
"C:\Program Files\Git\bin\git.exe" push --recurse-submodules=check --progress "origin" refs/heads/develop:refs/heads/develop
fatal: NullReferenceException encountered.
   Object reference not set to an instance of an object.
Username for 'https://myazureaccount.visualstudio.com': >> manual input >> myusername@mydomain.com
fatal: NullReferenceException encountered.
   Object reference not set to an instance of an object.
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 8 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 607 bytes | 607.00 KiB/s, done.
Total 7 (delta 5), reused 0 (delta 0)
remote: Analyzing objects... (7/7) (1901 ms)
remote: Storing packfile... done (36 ms)
remote: Storing index... done (34 ms)
To https://myazureaccount.visualstudio.com/DefaultCollection/MyProject/_git/MyProject
   8969ab204..bd56127f9  develop -> develop
Done

Press Enter or Esc to close console...
```

**Comment by nforss** [comment]
Nevermind, it seems the problem is with Git itself, and not with Git Extensions. The same problem arises when using Git from the command line.
