### ISSUE TITLE
.NET 5.0: `CommitInfo` varying indents

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9164]
`CommitInfo` has different indents. For `Parents:` it even depends on the commit.

![CommitInfo](https://user-images.githubusercontent.com/36601201/116617702-6efbe300-a93e-11eb-82f4-f366bc908513.png)

**Comment by GintasS** [comment]
I guess I take this once.

**Comment by GintasS** [comment]
So after a little bit of investigation, I have a few questions:

1. What should be the correct ident? Like this, a single tab between the longest string (Commit hash: in that case)

![image](https://user-images.githubusercontent.com/20372363/125807267-c1010c2a-6046-4198-9976-57c879555b4e.png)

2. I was debugging the tab logic for a few hours and found this:
The culprit is here: `(l % tabSize == 0 ? 0 : 1)` . It adds an additional tab the difference between desiredLength and the string is not a multiple of 4. 
3. In addition, I think this logic may be flawed in a sense, that it only tries to align a string based on a given constant and not on the longest string (with it's tabs too).
In this case, trying a test case while debugging (empty string - "" for example), will yield this (when the l % tabSize) was removed):

![image](https://user-images.githubusercontent.com/20372363/125809608-0bfbff62-c64f-4708-bfc1-42d91d355e57.png)

4. This task has .NET migration label attached, so I guess I might be even looking at a wrong place? Did this issue started to occur after the migration? Also, couldn't find any changes to `TabbedHeaderLabelFormatter.cs`, only the initial commits 2 years ago.

**Comment by gerhardol** [comment]
> Did this issue started to occur after the migration?

Yes, this _seem_ not to be in the last commits before .NET5 and is there after but the actual cause may be something else.

**Comment by RussKie** [comment]
> 1. What should be the correct ident? Like this, a single tab between the longest string (Commit hash: in that case)
> 
> ![image](https://user-images.githubusercontent.com/20372363/125807267-c1010c2a-6046-4198-9976-57c879555b4e.png)

The correct indent should be such that all text in the 2nd column is aligned.

> 1. This task has .NET migration label attached, so I guess I might be even looking at a wrong place? Did this issue started to occur after the migration? Also, couldn't find any changes to `TabbedHeaderLabelFormatter.cs`, [link here](https://github.com/gitextensions/gitextensions/blob/3bd6aec7b55fedb1c09027d7ff272fab5bbce819/ResourceManager/CommitDataRenders/TabbedHeaderLabelFormatter.cs), only the initial commits 2 years ago.

This issue surfaced after we migrated to .NET 5.


Also here's another place with issues (use can use 7f70caf3b14b19398e5ee95c31571a3f42c905bf to verify):
![image](https://user-images.githubusercontent.com/4403806/126029152-95430dd7-b8b5-439b-a4c7-d7473ad07156.png)

**Comment by gerhardol** [comment]
> Also here's another place with issues (use can use [7f70caf](https://github.com/gitextensions/gitextensions/commit/7f70caf3b14b19398e5ee95c31571a3f42c905bf) to verify):

This is how the submodule status have been displayed for years

**Comment by RussKie** [comment]
I believe at some point in time the text was aligned correctly

**Comment by GintasS** [comment]
To be honest, I'm bit struggling with this, because I can't find a specific thing that has changed in .NET 5.

Some more investigation:
```
1. Test: Render_with_tabs_and_links()

Expected:
"Author:\t\t\t<a href='mailto:John.Doe@test.com'>John Doe (Acme Inc) &lt;John.Doe@test.com&gt;</a>\r\n
Author date:\t3 days ago (7/22/2021 2:13:58 PM)\r\n
Committer:\t\t<a href='mailto:Jane.Doe@test.com'>Jane Doe &lt;Jane.Doe@test.com&gt;</a>\r\n
Commit date:\t2 days ago (7/23/2021 2:13:58 PM)\r\n
Commit hash:\t2713074a23000d5b24a7e1970bd09b8d393d4597\r\n
Children:\t\t<a href='gitext://gotocommit/3b6ce324e30ed7fda24483fd56a180c34a262202'>3b6ce324</a> <a href='gitext://gotocommit/2a8788ff15071a202505a96f80796dbff5750ddf'>2a8788ff</a> <a href='gitext://gotocommit/8e66fa8095a86138a7c7fb22318d2f819669831e'>8e66fa80</a>\r\n
Parents:\t\t<a href='gitext://gotocommit/2cb9353e332405b90d30ebf228761bf53e318ad3'>2cb9353e</a> <a href='gitext://gotocommit/48a4e7344dd14132501336062a3c82556ce19b90'>48a4e734</a>"

Actual:
"Author:\t\t<a href='mailto:John.Doe@test.com'>John Doe (Acme Inc) &lt;John.Doe@test.com&gt;</a>\r\n
Author date:\t3 days ago (7/22/2021 2:13:58 PM)\r\n
Committer:\t<a href='mailto:Jane.Doe@test.com'>Jane Doe &lt;Jane.Doe@test.com&gt;</a>\r\n
Commit date:\t2 days ago (7/23/2021 2:13:58 PM)\r\n
Commit hash:\t2713074a23000d5b24a7e1970bd09b8d393d4597\r\n
Children:\t<a href='gitext://gotocommit/3b6ce324e30ed7fda24483fd56a180c34a262202'>3b6ce324</a> <a href='gitext://gotocommit/2a8788ff15071a202505a96f80796dbff5750ddf'>2a8788ff</a> <a href='gitext://gotocommit/8e66fa8095a86138a7c7fb22318d2f819669831e'>8e66fa80</a>\r\n
Parents:\t\t<a href='gitext://gotocommit/2cb9353e332405b90d30ebf228761bf53e318ad3'>2cb9353e</a> <a href='gitext://gotocommit/48a4e7344dd14132501336062a3c82556ce19b90'>48a4e734</a>"

2. GitExtensions (with changes, running the program):
"Author:\t\t<a href='mailto:gerhardol@users.noreply.github.com'>Gerhard Olsson &lt;gerhardol@users.noreply.github.com&gt;</a>\r\n
Author date:\t2 months ago (5/20/2021 1:11:35 AM)\r\n
Commit date:\t2 months ago (5/27/2021 9:59:56 PM)\r\n
Commit hash:\tf964db16c6a2b142373ab1b86ccbfd9caae62be2\r\n
Child:\t\t<a href='gitext://gotocommit/284e069ee819291a269713cfa204e874ebd2c803'>284e069e</a>\r\n
Parent:\t\t<a href='gitext://gotocommit/096abaf87af8491410e7d5d4ab463daad0de0a6a'>096abaf8</a>"
```

Running 2. does render everything correctly (except maybe submodule status, this is a separate thing I think). 
So I'm thinking should that just be it, I'll fix failing tests and that's it. Since I don't really can't pinpoint what is wrong here

![image](https://user-images.githubusercontent.com/20372363/126897610-35b04ead-bebd-4fdc-9a71-67c92da41afa.png)

**Comment by gerhardol** [comment]
> To be honest, I'm bit struggling with this, because I can't find a specific thing that has changed in .NET 5.
> So I'm thinking should that just be it, I'll fix failing tests and that's it. Since I don't really can't pinpoint what is wrong here

The display should be fixed regardless...
Default tabSize changed?

**Comment by GintasS** [comment]
Searched a little bit more, now for commits, but couldn't find anything specific. Default tabSize hasn't changed, it has stayed the same since the initial commit.

Searched for TabbedHeaderLabelFormatter:
![image](https://user-images.githubusercontent.com/20372363/127768764-8a2aa0bc-f2fc-4222-b6c9-959c73b4bf5e.png)

Searched for CommitInfoHeader:
![image](https://user-images.githubusercontent.com/20372363/127768773-709d5b0b-2459-4ba7-bfa0-928e1b8292df.png)

But my previous argument stays, where the alignment is given an extra tab from ```(l % tabSize == 0 ? 0 : 1)```, it messes up the
alignment.



Author:		desiredLength: 16	tabSize: 4 	l: 9    tabs: 2 	extraTabSize: 1 
Author date:	desiredLength: 16	tabSize: 4	        l: 4    tabs: 1 	extraTabSize: 0
Commit date:	desiredLength: 16	tabSize: 4	        l: 4    tabs: 1	extraTabSize: 0
Commit hash:	desiredLength: 16	tabSize: 4  	l: 4    tabs: 1	extraTabSize: 0
Child:		desiredLength: 16	tabSize: 4 	l: 10  tabs: 2	extraTabSize: 1
Parent:		desiredLength: 16	tabSize: 4	        l: 9    tabs: 2	extraTabSize: 1

Red plus indicates that alignment is wrong. extraTabSize means that this statement was true: ```(l % tabSize == 0 ? 0 : 1)```
![image](https://user-images.githubusercontent.com/20372363/127769421-6da80458-baf1-4024-b81f-e21d59d2b680.png)

Next example:

Author:		desiredLength: 16	tabSize: 4	        l: 9	tabs: 2	extraTabSize: 1
Date:		desiredLength: 16	tabSize: 4	        l: 11	tabs: 2	extraTabSize: 1
Commiter:	desiredLength: 16	tabSize: 4	        l: 6	tabs: 1	extraTabSize: 1
Commit hash:	desiredLength: 16	tabSize: 4  	l: 4   tabs: 1	extraTabSize: 0
Parent:		desiredLength: 16	tabSize: 4 	l: 9   tabs: 2	extraTabSize: 1

![image](https://user-images.githubusercontent.com/20372363/127769451-533c464f-d722-4e4b-861c-1a5a9e3378b0.png)

**Comment by gerhardol** [comment]
I suggest to joust fix the indentation and hope it is working for all, addressing it later if required.

**Comment by RussKie** [comment]
Agree. Let's just get it fixed. I personally don't really care if those are
tabs or spaces, as long as the result  looks good ;)

**Comment by GintasS** [comment]
I've done even more digging, when trying to fix the failing tests because of my change. Been experimenting with Render_with_tabs_and_links in CommitDataHeaderRendererIntegrationTests.

Maybe this is a render problem? Or should I ignore this and just fix failing tests and that's it.

Conditions:
- I have removed the extra tab thing ```(l % tabSize == 0 ? 0 : 1)```.

![image](https://user-images.githubusercontent.com/20372363/128349677-b5146c03-b7ef-4c2e-8c3f-ec299c31cab2.png)

**Comment by RussKie** [comment]
There was a change in .NET Framework 4.7.1 which used a newer RichEdit
control. .NET uses the same newer control too. So it is plausible that it
had a change in rendering logic....
Fix the test and call it job done :)

**Comment by GintasS** [comment]
By the way, this PR does not fix the submodule status problem.

> > 1. What should be the correct ident? Like this, a single tab between the longest string (Commit hash: in that case)
> > 
> > ![image](https://user-images.githubusercontent.com/20372363/125807267-c1010c2a-6046-4198-9976-57c879555b4e.png)
> 
> The correct indent should be such that all text in the 2nd column is aligned.
> 
> > 1. This task has .NET migration label attached, so I guess I might be even looking at a wrong place? Did this issue started to occur after the migration? Also, couldn't find any changes to `TabbedHeaderLabelFormatter.cs`, [link here](https://github.com/gitextensions/gitextensions/blob/3bd6aec7b55fedb1c09027d7ff272fab5bbce819/ResourceManager/CommitDataRenders/TabbedHeaderLabelFormatter.cs), only the initial commits 2 years ago.
> 
> This issue surfaced after we migrated to .NET 5.
> 
> Also here's another place with issues (use can use [7f70caf](https://github.com/gitextensions/gitextensions/commit/7f70caf3b14b19398e5ee95c31571a3f42c905bf) to verify):
> ![image](https://user-images.githubusercontent.com/4403806/126029152-95430dd7-b8b5-439b-a4c7-d7473ad07156.png)

**Comment by RussKie** [comment]
@GintasS looks like I found few cases where the fix is still not working as intended. E.g. the following are observed in Russian language built from the current master

1. b8b8e4cef6f2c86d2f27cc14e30cd7877edcb417 
![image](https://user-images.githubusercontent.com/4403806/131252022-906199b6-c72a-42f0-8676-71a26057f4ac.png)

2. 72c68245dbdba641e229d6f713d7874545773708 - looks like the "Children" label text is completely missing, but the value column is nonetheless incorrectly indented.
![image](https://user-images.githubusercontent.com/4403806/131252164-8aaedb5a-4930-4b55-a1f3-ad0d1ee23caa.png)

**Comment by GintasS** [comment]
Oh wow, I thought I have fixed it, will need to go back.

**Comment by mdonatas** [comment]
Tried GE with net6.0 for fun and no profit and RU seems OK. 200% DPI.
![image](https://user-images.githubusercontent.com/483659/133293295-91c889ff-e071-4aeb-a7b3-0d74fb932a36.png)

**Comment by RussKie** [comment]
The issue doesn't manifest for every commit. Check if you get it to repro
at the commits I identified.

**Comment by mdonatas** [comment]
You are right, I could repro with commits you've mentioned but `72c6824` looked like `b8b8e4c` and not like in the screenshots. Still not right though.
